server:
  port: 8989

---
spring:
  application:
    name: cloud-native-spring-ui
  datasource:
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  main:
    allow-bean-definition-overriding: true


info: # add this section
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

feign:
  httpclient:
    disableSslValidation: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

---
spring:
  profiles: cloud

feign:
  httpclient:
    disableSslValidation: false

management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true

